Add All
eng-mohamed-eldeeb/Covid pull request #1
Opened 2022-04-29 02:27 UTC by eng-mohamed-eldeeb

Home page

When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
Along with the category name, you will display some numeric values per category that come from the API.
When the user clicks (or taps) on a category item, the application navigates to the details page.
Details page

In the details page, the webapp retrieves data from the API to show detailed data in the category.
When the user clicks on the "Back" button (<), the user navigates to the home page.

2022-04-29 04:23 UTC, medaminedev66 requested changes
Hi @eng-mohamed-eldeeb  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The home page design looks great and matches the Figma design
- Your code organization was really good
- There are no linter errors 
- You have a descriptive PR
- The project uses Redux for state management and data retrieved from the API are stored in the Redux store correctly. Great job.

## Required Changes ♻️
- [ ] Kindly remove all the unused files from your repository:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/77190203/165882780-07c09a05-916b-408e-b901-273227bc5695.png">

- [ ] Pull Request should have a descriptive title telling others what changes are inside. Please update that.

- [ ] In the future, It would be better to write more commit messages. Having periodic commits means that you can understand how you broke something and it will be easy to debug your app using the bisect tool.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 04:23 UTC, medaminedev66 commented on README.md
> +> #### A web application for a company whcih provides commercial and scientific space travel services. In this application users can book rockets and join the space missions useing live data from the
- [x] Please change the description of the project to represent the 'Covid' app rather than the 'space travel' app.

2022-04-29 04:23 UTC, medaminedev66 commented on README.md
> +Then `cd space-travelers`
- [ ] Please change the link of the repo to the link of the covid repository.
- [ ] The same thing with `cd space-travlers`, try to change it to the name of the current project.

2022-04-29 04:23 UTC, medaminedev66 commented on src/Component/Region.js
> +export default Region;
- [ ] Following the project requirements, you should follow the [design guideline](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)) for the detail page. As far as I can tell, you're using the same design for the detail page as you are for the home page. Take a look at the following comparison:
- Original design:
<img width="307" alt="image" src="https://user-images.githubusercontent.com/77190203/165883978-450ed637-cbcd-494d-9eba-0d322a6eaa97.png">

- Your detail page design:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/77190203/165884042-06856f94-dd0d-44ca-8a4b-5d9ace428715.png">

2022-04-30 05:59 UTC, bini-i requested changes
# Status: Changes Required :yellow_circle:            
### Hello @eng-mohamed-eldeeb   :wave: 

Thanks for working on the requirements suggested by the previous reviewer, but there are still some which aren't addressed yet.

## To highlight
- Repo and linter setup professionally
- Good organization of files under meaningful directories
- React routing works flawlessly 
- Good use of `useSelector` to connect to redux 
## To improve
- As the previous reviewer suggested unused files are still in the repo, You can refer here for more on how to [remove files from git remote](https://devconnected.com/how-to-delete-file-on-git/)

_Kindly check inline comments below :point_down: _

## Optional suggestions
[_OPTIONAL_] 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

#### If you have any questions feel free to ask within the PR thread.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

2022-04-30 05:59 UTC, bini-i commented on src/Component/Region.js
> +  );
- [ ] As the previous reviewer suggested the layout for the region component is the same as the home component, kindly use similar layout as the one given in design guidelines:
- Your design 
![image](https://user-images.githubusercontent.com/61377322/166093382-66ceeb4a-c49c-4647-b8e1-ad3d0e0e236f.png)
- Design guideline (Kindly notice how the details are laid out horizontally opposed to the home page layout)
![image](https://user-images.githubusercontent.com/61377322/166093450-816713c8-eaa8-4c66-806f-2b11b2cc2336.png)

2022-04-30 05:59 UTC, bini-i commented on public/index.html
> +    <title>Space Travelers</title>
- [ ] [**_OPTIONAL_**]Please customize the meta and title for the index.html to be specific to your project, currently the title is Space Travelers, I thing Covid metric is a better title.
![image](https://user-images.githubusercontent.com/61377322/166093616-a4eb1c61-07d0-4266-884f-c287ff77b30a.png)

2022-04-30 06:58 UTC, medaminedev66 approved these changes
Hi @eng-mohamed-eldeeb, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Suggestions
- Please remember to remove all unneeded files from your repository to keep it looking professional.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-30 07:01 UTC, merged